import ipaddress
import re
from enum import Enum

from pydantic import Field, field_validator

from frigate.util.time import posix_timezone

from ..base import FrigateBaseModel
from ..env import EnvString
from .objects import DEFAULT_TRACKED_OBJECTS

__all__ = [
    "GlobalOnvifConfig",
    "OnvifConfig",
    "OnvifTimeSyncConfig",
    "PtzAutotrackConfig",
    "ZoomingModeEnum",
]

HOSTNAME_PATTERN = re.compile(
    r"^(?=.{1,253}$)[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*\.?$"
)


class ZoomingModeEnum(str, Enum):
    disabled = "disabled"
    absolute = "absolute"
    relative = "relative"


class PtzAutotrackConfig(FrigateBaseModel):
    enabled: bool = Field(
        default=False,
        title="Enable Autotracking",
        description="Enable or disable automatic PTZ camera tracking of detected objects.",
    )
    calibrate_on_startup: bool = Field(
        default=False,
        title="Calibrate on start",
        description="Measure PTZ motor speeds on startup to improve tracking accuracy. Frigate will update config with movement_weights after calibration.",
    )
    zooming: ZoomingModeEnum = Field(
        default=ZoomingModeEnum.disabled,
        title="Zoom mode",
        description="Control zoom behavior: disabled (pan/tilt only), absolute (most compatible), or relative (concurrent pan/tilt/zoom).",
    )
    zoom_factor: float = Field(
        default=0.3,
        title="Zoom factor",
        description="Control zoom level on tracked objects. Lower values keep more scene in view; higher values zoom in closer but may lose tracking. Values between 0.1 and 0.75.",
        ge=0.1,
        le=0.75,
    )
    track: list[str] = Field(
        default=DEFAULT_TRACKED_OBJECTS,
        title="Tracked objects",
        description="List of object types that should trigger autotracking.",
    )
    required_zones: list[str] = Field(
        default_factory=list,
        title="Required zones",
        description="Objects must enter one of these zones before autotracking begins.",
    )
    return_preset: str = Field(
        default="home",
        title="Return preset",
        description="ONVIF preset name configured in camera firmware to return to after tracking ends.",
    )
    timeout: int = Field(
        default=10,
        title="Return timeout",
        description="Wait this many seconds after losing tracking before returning camera to preset position.",
    )
    stream_latency: float | None = Field(
        default=None,
        title="Stream latency",
        description="Seconds the video keeps showing a PTZ move after the camera reports it finished. Leave unset to measure it after every move.",
        ge=0.0,
        le=5.0,
    )
    movement_weights: str | list[str] | None = Field(
        default_factory=list,
        title="Movement weights",
        description="Calibration values automatically generated by camera calibration. Do not modify manually.",
    )
    enabled_in_config: bool | None = Field(
        default=None,
        title="Original autotrack state",
        description="Internal field to track whether autotracking was enabled in configuration.",
    )

    @field_validator("movement_weights", mode="before")
    @classmethod
    def validate_weights(cls, v):
        if v is None:
            return None

        if isinstance(v, str):
            weights = list(map(str, map(float, v.split(","))))
        elif isinstance(v, list):
            weights = [str(float(val)) for val in v]
        else:
            raise ValueError("Invalid type for movement_weights")

        if len(weights) != 6:
            raise ValueError(
                "movement_weights must have exactly 6 floats, remove this line from your config and run autotracking calibration"
            )

        return weights


class OnvifTimeSyncConfig(FrigateBaseModel):
    enabled: bool = Field(
        default=False,
        title="Enable time sync",
        description="Set the NTP server and timezone below on the camera at startup and whenever this setting changes. Requires an ONVIF user with administrator rights.",
    )
    ntp_server: str | None = Field(
        default=None,
        title="NTP server",
        description="Hostname or IP address of the NTP server the camera synchronizes its clock with. Leave empty to keep the camera's NTP settings.",
    )
    timezone: str | None = Field(
        default=None,
        title="Timezone",
        description="Timezone for the camera, either a name such as Europe/Moscow or an offset such as UTC+3. Leave empty to keep the camera's timezone.",
    )

    @field_validator("ntp_server", "timezone", mode="before")
    @classmethod
    def empty_as_none(cls, v):
        if isinstance(v, str):
            return v.strip() or None

        return v

    @field_validator("ntp_server")
    @classmethod
    def validate_ntp_server(cls, v: str | None) -> str | None:
        if v is None:
            return v

        try:
            ipaddress.ip_address(v)
            return v
        except ValueError:
            pass

        if not HOSTNAME_PATTERN.match(v):
            raise ValueError(
                f"Invalid NTP server {v}, expected a hostname or IP address"
            )

        return v

    @field_validator("timezone")
    @classmethod
    def validate_timezone(cls, v: str | None) -> str | None:
        if v is not None:
            # raises ValueError with the reason for an unusable timezone
            posix_timezone(v)

        return v


class OnvifConfig(FrigateBaseModel):
    host: EnvString = Field(
        default="",
        title="ONVIF host",
        description="Host (and optional scheme) for the ONVIF service for this camera.",
    )
    port: int = Field(
        default=8000,
        title="ONVIF port",
        description="Port number for the ONVIF service.",
    )
    user: EnvString | None = Field(
        default=None,
        title="ONVIF username",
        description="Username for ONVIF authentication; some devices require admin user for ONVIF.",
    )
    password: EnvString | None = Field(
        default=None,
        title="ONVIF password",
        description="Password for ONVIF authentication.",
    )
    tls_insecure: bool = Field(
        default=False,
        title="Disable TLS verify",
        description="Skip TLS verification and disable digest auth for ONVIF (unsafe; use in safe networks only).",
    )
    profile: str | None = Field(
        default=None,
        title="ONVIF profile",
        description="Specific ONVIF media profile to use for PTZ control, matched by token or name. If not set, the first profile with valid PTZ configuration is selected automatically.",
    )
    autotracking: PtzAutotrackConfig = Field(
        default_factory=PtzAutotrackConfig,
        title="Autotracking",
        description="Automatically track moving objects and keep them centered in the frame using PTZ camera movements.",
    )
    ignore_time_mismatch: bool = Field(
        default=False,
        title="Ignore time mismatch",
        description="Ignore time synchronization differences between camera and Frigate server for ONVIF communication.",
    )
    time_sync: OnvifTimeSyncConfig = Field(
        default_factory=OnvifTimeSyncConfig,
        title="Time sync",
        description="NTP server and timezone that Frigate sets on the camera over ONVIF.",
    )


class GlobalOnvifConfig(FrigateBaseModel):
    time_sync: OnvifTimeSyncConfig = Field(
        default_factory=OnvifTimeSyncConfig,
        title="Time sync",
        description="NTP server and timezone that Frigate sets on the camera over ONVIF.",
    )
